import { Urbanist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import PrivyWrapper from "@/privy/privyProvider";
import Header from "@/components/header";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <PrivyWrapper>
          <Header />
          {children}
          <Toaster />
        </PrivyWrapper>
      </body>
    </html>
  );
}
